[versions]

minSdk = "21"
compileSdk = "34"
sonner = "0.3.6"
targetSdk = "34"

kotlin = "2.0.0"
dependencyCheckPluginVersion = "0.51.0"
agp = "8.3.2"
mavenPublish = "0.28.0"

composeViewModel = "2.8.2"
activityCompose = "1.9.0"

material = "1.12.0"
lifecycleRuntimeKtx = "2.8.2"

ksp = "2.0.0-1.0.21"

junit = "4.13.2"

compose = "1.7.0-beta03"
composeMaterial = "1.7.0-beta03"
composeNavigationMaterial = "1.7.0-beta01"
kmpComposeNavigation = "2.8.0-alpha02"
kmpComposeVMLifecycle = "2.8.0"
kmpBundle = "1.0.0"

ktxSerialization = "1.6.3"
mockk = "1.13.9"

compileTesting = "1.6.0"
composeWear = "1.3.1"

[plugins]
dependencyCheckPlugin = { id = "com.github.ben-manes.versions", version.ref = "dependencyCheckPluginVersion" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }

jetbrainsCompose = { id = "org.jetbrains.compose", version = "1.6.10" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]

# Gradle
gradle-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublish"}

# Android
androidMaterial = { module = "com.google.android.material:material", version.ref = "material" }

# AndroidX
androidx-lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

# Compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
compose-material-navigation = { module = "androidx.compose.material:material-navigation", version.ref = "composeNavigationMaterial" }
compose-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "composeViewModel" }
kmp-compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "kmpComposeNavigation" }
kmp-compose-vm = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "kmpComposeVMLifecycle" }
kmp-bundle = { module = "org.jetbrains.androidx.core:core-bundle", version.ref = "kmpBundle" }
toaster = { module = "io.github.dokar3:sonner", version.ref = "sonner" }

# Ksp
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

# KtxSerialization
ktxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "ktxSerialization" }

# Test
test-junit = { module = "junit:junit", version.ref = "junit" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
test-kotlinCompile = { module = "com.github.tschuchortdev:kotlin-compile-testing", version.ref = "compileTesting" }
test-kotlinCompileKsp = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version.ref = "compileTesting" }

# Wear

wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "composeWear" }
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "composeWear" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "composeWear" }
wear-input = { module = "androidx.wear:wear-input", version = "1.1.0" }
